### ISSUE TITLE
想请教一个关于location的问题..

### ISSUE THREAD

**Issue by menyouneko** [crane-yuan/delmyweibo#1]
你好,我看了一下删除微博的js代码,发现其中有一句: 
window.location.href = url;
这样子跳转之后,为什么还能执行后面的语句?
跳转之后不是相当于跳到一个新的页面吗?

**Comment by craneyuan** [comment]
关于这句`window.location.href = url;`执行之后，并不是直接跳转到一个新的页面，它只是刷新了当前页面的URL地址，是一次重定向操作。

你可能把`Window.location.href ()` 和 `Window.open ()`搞混淆了。你可以参考下这个问题[Window.location.href () and Window.open () in JavaScript](http://stackoverflow.com/questions/18634383/window-location-href-and-window-open-in-javascript)

**Comment by menyouneko** [comment]
谢谢回复~
window.location.href 和window.open这两个我也在控制台实际试了一下，
window.open()会打开一个新的标签页，对旧的标签页页面没有影响；
而window.location.href是在当前标签页刷新URL，以微博为例，我只改变URL地址的一个参数，然后通过window.location.href刷新，页面的数据也会跟着刷新。不是很理解的是，这样刷新之后是如何保证会接着执行之后的代码。
（另外补充一点，我直接把你delweibo.user.js的代码放到控制台执行，只会执行删除一次...这个就更不理解了...回头再研究研究看看。）
再次感谢回复~

**Comment by craneyuan** [comment]
首先，谢谢你的反馈。

关于『不是很理解的是，这样刷新之后是如何保证会接着执行之后的代码。』这个问题，我的理解是刷新操作是异步的，所以后面的代码依然可以执行到。

关于『delweibo.user.js放到控制台执行，只会执行删除一次』这个问题，我确实没有注意到，我之后会再测试一下代码的 :smile: 。
