### ISSUE TITLE
提交一个小建议

### ISSUE THREAD

**Issue by Arduns** [crane-yuan/delmyweibo#2]
我用了你的方法帮朋友删微博，原以为可以直接自动删除但是渣浪要么没有数据要么加载中，然后我增加了一个自动刷新页面的语句来改善这个问题
window.setInterval(function(){
     window.location.reload(); //1分钟刷新一次页面
},1*60*1000)

**Comment by craneyuan** [comment]
@Arduns 首先，谢谢你的反馈！ 😄 另外，我在测试代码时，删除一条微博之后，它是会自动刷新一下的，或许是网络问题，刷新不及时吧！我再测试一下。
